import type { ExampleSentence } from '../types'

/** Sentences that make up the four Level 6 reading passages (see
 *  content/passages/passages.ts). These are original, author-composed
 *  practice passages built from already-verified vocabulary and grammar —
 *  NOT excerpts from a real published/news source (an AI author should not
 *  fabricate a false provenance for "authentic" text). This mirrors how
 *  every other example sentence in this corpus is built: composed, not
 *  claimed to be quoted from somewhere real, with each grammatical
 *  construction independently checked against reference grammar sources.
 *  See PROGRESS.md for this design decision written out in full. */
export const passageSentences: ExampleSentence[] = [
  // ---- Passage 1: زندگی روزمره در تهران (Daily life in Tehran) ----
  { id: 's-p1-1', fa: 'مریم هر روز صبح زود از خواب بیدار می‌شود.', translit: 'maryam har ruz sobh-e zud az khāb bidār mishavad.', en: 'Maryam wakes up early every morning.', literalEn: 'Maryam every day morning early from sleep awake becomes', register: 'formal', level: 6, words: [{ fa: 'مریم', translit: 'maryam', en: 'Maryam (name)' }, { fa: 'هر روز صبح زود', translit: 'har ruz sobh-e zud', en: 'every morning early' }, { fa: 'از خواب بیدار می‌شود', translit: 'az khāb bidār mishavad', en: 'wakes up', vocabId: 'daily-bidaar-shodan' }], vocabIds: ['daily-bidaar-shodan'], confidence: 'high-confidence' },
  { id: 's-p1-2', fa: 'او ابتدا صبحانه می‌خورد و بعد به سر کار می‌رود.', translit: 'u ebtedā sobhāne mikhorad va ba\'d be sar-e kār miravad.', en: 'First she eats breakfast, then goes to work.', literalEn: 'she first breakfast eats and after to head-of work goes', register: 'formal', level: 6, words: [{ fa: 'او ابتدا صبحانه می‌خورد', translit: 'u ebtedā sobhāne mikhorad', en: 'first she eats breakfast', vocabId: 'daily-sohbat' }, { fa: 'و بعد به سر کار می‌رود', translit: "va ba'd be sar-e kār miravad", en: 'and then goes to work', vocabId: 'work-kar' }], vocabIds: ['daily-sohbat', 'work-kar'], confidence: 'high-confidence' },
  { id: 's-p1-3', fa: 'اداره‌ی او در مرکز شهر است و ترافیک تهران معمولاً سنگین است.', translit: "edāre-ye u dar markaz-e shahr ast va terāfik-e tehrān ma'mulan sangin ast.", en: "Her office is downtown, and Tehran's traffic is usually heavy.", literalEn: 'office-of her in center-of city is and traffic-of Tehran usually heavy is', register: 'formal', level: 6, words: [{ fa: 'اداره‌ی او در مرکز شهر است', translit: 'edāre-ye u dar markaz-e shahr ast', en: 'her office is downtown', vocabId: 'work-edare' }, { fa: 'و ترافیک تهران معمولاً سنگین است', translit: "va terāfik-e tehrān ma'mulan sangin ast", en: "and Tehran's traffic is usually heavy" }], vocabIds: ['work-edare'], confidence: 'high-confidence' },
  { id: 's-p1-4', fa: 'اگرچه راه دور است، مریم ترجیح می‌دهد با مترو برود.', translit: 'agarche rāh dur ast, maryam tarjih midahad bā metro beravad.', en: "Although it's far, Maryam prefers to go by metro.", literalEn: 'although way far is, Maryam preference gives with metro she-go[subj.]', register: 'formal', level: 6, words: [{ fa: 'اگرچه راه دور است', translit: 'agarche rāh dur ast', en: "although it's far", vocabId: 'dir-dur' }, { fa: 'مریم ترجیح می‌دهد', translit: 'maryam tarjih midahad', en: 'Maryam prefers' }, { fa: 'با مترو برود', translit: 'bā metro beravad', en: 'to go by metro', vocabId: 'trav-metro' }], grammarConceptIds: ['g-concessive-clauses'], vocabIds: ['dir-dur', 'trav-metro'], confidence: 'high-confidence' },
  { id: 's-p1-5', fa: 'عصرها او با دوستانش در یک کافه می‌نشیند و چای می‌خورد.', translit: "asrhā u bā dustānash dar yek kāfe mineshinad va chāy mikhorad.", en: 'In the evenings she sits with her friends at a café and drinks tea.', literalEn: 'evenings she with her-friends in a café sits and tea drinks', register: 'formal', level: 6, words: [{ fa: 'عصرها او با دوستانش', translit: 'asrhā u bā dustānash', en: 'in the evenings, she with her friends', vocabId: 'fam-dust' }, { fa: 'در یک کافه می‌نشیند', translit: 'dar yek kāfe mineshinad', en: 'sits at a café' }, { fa: 'و چای می‌خورد', translit: 'va chāy mikhorad', en: 'and drinks tea', vocabId: 'food-chay' }], vocabIds: ['fam-dust', 'food-chay'], confidence: 'high-confidence' },
  { id: 's-p1-6', fa: 'زندگی در تهران پرمشغله است، اما مریم آن را دوست دارد.', translit: 'zendegi dar tehrān por-mashghale ast, ammā maryam ān rā dust dārad.', en: 'Life in Tehran is busy, but Maryam loves it.', literalEn: 'life in Tehran busy is, but Maryam it [obj.] friend has', register: 'formal', level: 6, words: [{ fa: 'زندگی در تهران پرمشغله است', translit: 'zendegi dar tehrān por-mashghale ast', en: 'life in Tehran is busy' }, { fa: 'اما مریم آن را دوست دارد', translit: 'ammā maryam ān rā dust dārad', en: 'but Maryam loves it' }], grammarConceptIds: ['g-object-marker-ra'], confidence: 'high-confidence' },

  // ---- Passage 2: نامه‌ای از یک دوست (A letter from a friend) ----
  { id: 's-p2-1', fa: 'دوست عزیزم، امیدوارم حالت خوب باشد.', translit: 'dust-e azizam, omidvāram hālet khub bāshad.', en: 'My dear friend, I hope you are well.', literalEn: 'friend dear-my, hopeful-am your-state good be[subj.]', register: 'literary', level: 6, words: [{ fa: 'دوست عزیزم', translit: 'dust-e azizam', en: 'my dear friend' }, { fa: 'امیدوارم', translit: 'omidvāram', en: 'I hope' }, { fa: 'حالت خوب باشد', translit: 'hālet khub bāshad', en: 'that you are well' }], grammarConceptIds: ['g-subjunctive'], confidence: 'high-confidence' },
  { id: 's-p2-2', fa: 'چند ماه پیش به شهر جدیدی نقل مکان کردم.', translit: 'chand māh pish be shahr-e jadidi naghl-e makān kardam.', en: 'A few months ago I moved to a new city.', literalEn: 'a-few month ago to city new relocation I-did', register: 'literary', level: 6, words: [{ fa: 'چند ماه پیش', translit: 'chand māh pish', en: 'a few months ago', vocabId: 'time-mah' }, { fa: 'به شهر جدیدی', translit: 'be shahr-e jadidi', en: 'to a new city', vocabId: 'adj-jadid' }, { fa: 'نقل مکان کردم', translit: 'naghl-e makān kardam', en: 'I moved' }], vocabIds: ['time-mah', 'adj-jadid'], confidence: 'high-confidence' },
  { id: 's-p2-3', fa: 'چون هیچ‌کس را نمی‌شناختم، اول کمی احساس تنهایی می‌کردم.', translit: 'chon hich-kas rā nemishenākhtam, avval kami ehsās-e tanhāyi mikardam.', en: "Because I didn't know anyone, at first I felt a bit lonely.", literalEn: 'because no-one [obj.] I-didn\'t-know, first a-little feeling-of loneliness I-was-doing', register: 'literary', level: 6, words: [{ fa: 'چون هیچ‌کس را نمی‌شناختم', translit: 'chon hich-kas rā nemishenākhtam', en: "because I didn't know anyone" }, { fa: 'اول کمی احساس تنهایی می‌کردم', translit: 'avval kami ehsās-e tanhāyi mikardam', en: 'at first I felt a bit lonely' }], grammarConceptIds: ['g-causal-clauses', 'g-imperfect-past'], confidence: 'high-confidence' },
  { id: 's-p2-4', fa: 'اما کم‌کم با همسایه‌هایم آشنا شدم و زندگی بهتر شد.', translit: 'ammā kam-kam bā hamsāye-hāyam āshnā shodam va zendegi behtar shod.', en: 'But little by little I got to know my neighbors, and life got better.', literalEn: 'but little-by-little with my-neighbors acquainted I-became and life better became', register: 'literary', level: 6, words: [{ fa: 'اما کم‌کم با همسایه‌هایم آشنا شدم', translit: 'ammā kam-kam bā hamsāye-hāyam āshnā shodam', en: 'but little by little I got to know my neighbors' }, { fa: 'و زندگی بهتر شد', translit: 'va zendegi behtar shod', en: 'and life got better', vocabId: 'home-khane' }], grammarConceptIds: ['g-comparison'], confidence: 'high-confidence' },
  { id: 's-p2-5', fa: 'هفته‌ی پیش یک دوست جدید پیدا کردم که او هم عاشق کتاب است.', translit: 'hafte-ye pish yek dust-e jadid peydā kardam ke u ham āsheq-e ketāb ast.', en: 'Last week I found a new friend who also loves books.', literalEn: 'week-of past one friend new found I-did that she too lover-of book is', register: 'literary', level: 6, words: [{ fa: 'هفته‌ی پیش یک دوست جدید پیدا کردم', translit: 'hafte-ye pish yek dust-e jadid peydā kardam', en: 'last week I found a new friend', vocabId: 'time-hafte' }, { fa: 'که او هم عاشق کتاب است', translit: 'ke u ham āsheq-e ketāb ast', en: 'who also loves books', vocabId: 'sch-ketab' }], grammarConceptIds: ['g-relative-clauses'], vocabIds: ['time-hafte', 'sch-ketab'], confidence: 'high-confidence' },
  { id: 's-p2-6', fa: 'امیدوارم به‌زودی همدیگر را ببینیم.', translit: "omidvāram be-zudi hamdigar rā bebinim.", en: 'I hope we see each other soon.', literalEn: "hopeful-am soon each-other [obj.] we-see[subj.]", register: 'literary', level: 6, words: [{ fa: 'امیدوارم', translit: 'omidvāram', en: 'I hope' }, { fa: 'به‌زودی همدیگر را ببینیم', translit: 'be-zudi hamdigar rā bebinim', en: 'that we see each other soon' }], grammarConceptIds: ['g-subjunctive', 'g-object-marker-ra'], confidence: 'high-confidence' },

  // ---- Passage 3: هوا و فصل‌ها در ایران (Weather and seasons in Iran) ----
  { id: 's-p3-1', fa: 'ایران چهار فصل مشخص دارد: بهار، تابستان، پاییز و زمستان.', translit: 'irān chahār fasl-e moshakhkhas dārad: bahār, tābestān, pā\'iz va zemestān.', en: 'Iran has four distinct seasons: spring, summer, autumn, and winter.', literalEn: 'Iran four season-of distinct has: spring, summer, autumn and winter', register: 'formal', level: 6, words: [{ fa: 'ایران چهار فصل مشخص دارد', translit: 'irān chahār fasl-e moshakhkhas dārad', en: 'Iran has four distinct seasons', vocabId: 'weath-fasl' }, { fa: 'بهار، تابستان، پاییز و زمستان', translit: "bahār, tābestān, pā'iz va zemestān", en: 'spring, summer, autumn, and winter', vocabId: 'weath-bahar' }], vocabIds: ['weath-fasl', 'weath-bahar', 'weath-tabestan', 'weath-paeez', 'weath-zemestan'], confidence: 'high-confidence' },
  { id: 's-p3-2', fa: 'بهار معمولاً هوای معتدل و بارانی دارد.', translit: "bahār ma'mulan havā-ye mo'tadel va bārāni dārad.", en: 'Spring usually has mild, rainy weather.', literalEn: 'spring usually weather-of mild and rainy has', register: 'formal', level: 6, words: [{ fa: 'بهار معمولاً', translit: "bahār ma'mulan", en: 'spring usually', vocabId: 'weath-bahar' }, { fa: 'هوای معتدل و بارانی دارد', translit: "havā-ye mo'tadel va bārāni dārad", en: 'has mild, rainy weather', vocabId: 'nat-baran' }], vocabIds: ['weath-bahar', 'nat-baran'], confidence: 'high-confidence' },
  { id: 's-p3-3', fa: 'تابستان در بیشتر شهرها گرم است، اما در شمال کشور مرطوب‌تر است.', translit: 'tābestān dar bishtar-e shahrhā garm ast, ammā dar shomāl-e keshvar martub-tar ast.', en: "Summer is hot in most cities, but it's more humid in the north of the country.", literalEn: 'summer in most-of cities hot is, but in north-of country more-humid is', register: 'formal', level: 6, words: [{ fa: 'تابستان در بیشتر شهرها گرم است', translit: 'tābestān dar bishtar-e shahrhā garm ast', en: 'summer is hot in most cities', vocabId: 'weath-tabestan' }, { fa: 'اما در شمال کشور مرطوب‌تر است', translit: 'ammā dar shomāl-e keshvar martub-tar ast', en: "but it's more humid in the north", vocabId: 'weath-rotoobat' }], grammarConceptIds: ['g-comparison'], vocabIds: ['weath-tabestan', 'weath-rotoobat'], confidence: 'high-confidence' },
  { id: 's-p3-4', fa: 'پاییز فصل مورد علاقه‌ی خیلی از ایرانی‌هاست، چون هوا خنک و آسمان صاف است.', translit: "pā'iz fasl-e mored-e alāghe-ye kheyli az irāni-hāst, chon havā khonak va āsemān sāf ast.", en: "Autumn is many Iranians' favorite season, because the weather is cool and the sky is clear.", literalEn: 'autumn season-of interest-of many of Iranians-is, because weather cool and sky clear is', register: 'formal', level: 6, words: [{ fa: 'پاییز فصل مورد علاقه‌ی خیلی از ایرانی‌هاست', translit: "pā'iz fasl-e mored-e alāghe-ye kheyli az irāni-hāst", en: "autumn is many Iranians' favorite season", vocabId: 'weath-paeez' }, { fa: 'چون هوا خنک و آسمان صاف است', translit: 'chon havā khonak va āsemān sāf ast', en: 'because the weather is cool and the sky is clear' }], grammarConceptIds: ['g-causal-clauses'], vocabIds: ['weath-paeez'], confidence: 'high-confidence' },
  { id: 's-p3-5', fa: 'زمستان در کوهستان‌ها برفی است، اما در جنوب معمولاً برف نمی‌بارد.', translit: "zemestān dar kuhestān-hā barfi ast, ammā dar jonub ma'mulan barf nemibārad.", en: "Winter is snowy in the mountains, but it usually doesn't snow in the south.", literalEn: 'winter in mountains snowy is, but in south usually snow it-not-rains', register: 'formal', level: 6, words: [{ fa: 'زمستان در کوهستان‌ها برفی است', translit: 'zemestān dar kuhestān-hā barfi ast', en: 'winter is snowy in the mountains', vocabId: 'weath-zemestan' }, { fa: 'اما در جنوب معمولاً برف نمی‌بارد', translit: "ammā dar jonub ma'mulan barf nemibārad", en: "but it usually doesn't snow in the south", vocabId: 'dir-jonub' }], vocabIds: ['weath-zemestan', 'dir-jonub'], confidence: 'high-confidence' },

  // ---- Passage 4: داستان کوتاه — پیرمرد و باغش (Short story: the old man and his garden) ----
  { id: 's-p4-1', fa: 'در دهکده‌ای کوچک، پیرمردی زندگی می‌کرد که باغی زیبا داشت.', translit: "dar dehkade-i kuchik, pirmardi zendegi mikard ke bāghi zibā dāsht.", en: 'In a small village lived an old man who had a beautiful garden.', literalEn: 'in a-village small, an-old-man life was-doing that a-garden beautiful had', register: 'literary', level: 6, words: [{ fa: 'در دهکده‌ای کوچک', translit: 'dar dehkade-i kuchik', en: 'in a small village' }, { fa: 'پیرمردی زندگی می‌کرد', translit: 'pirmardi zendegi mikard', en: 'an old man lived' }, { fa: 'که باغی زیبا داشت', translit: "ke bāghi zibā dāsht", en: 'who had a beautiful garden', vocabId: 'adj-ziba' }], grammarConceptIds: ['g-relative-clauses', 'g-imperfect-past'], vocabIds: ['adj-ziba'], confidence: 'high-confidence' },
  { id: 's-p4-2', fa: 'او هر روز صبح به باغ می‌رفت و به گل‌ها آب می‌داد.', translit: "u har ruz sobh be bāgh miraft va be gol-hā āb midād.", en: 'Every morning he would go to the garden and water the flowers.', literalEn: 'he every day morning to garden was-going and to flowers water was-giving', register: 'literary', level: 6, words: [{ fa: 'او هر روز صبح به باغ می‌رفت', translit: 'u har ruz sobh be bāgh miraft', en: 'every morning he would go to the garden' }, { fa: 'و به گل‌ها آب می‌داد', translit: "va be gol-hā āb midād", en: 'and water the flowers', vocabId: 'nat-gol' }], grammarConceptIds: ['g-imperfect-past'], vocabIds: ['nat-gol'], confidence: 'high-confidence' },
  { id: 's-p4-3', fa: 'اگرچه پیر و خسته بود، هرگز از کار در باغ دست نمی‌کشید.', translit: "agarche pir o khaste bud, hargez az kār dar bāgh dast nemikeshid.", en: 'Although he was old and tired, he never gave up working in the garden.', literalEn: 'although old and tired he-was, never from work in garden hand was-not-pulling', register: 'literary', level: 6, words: [{ fa: 'اگرچه پیر و خسته بود', translit: 'agarche pir o khaste bud', en: 'although he was old and tired', vocabId: 'adj-khaste' }, { fa: 'هرگز از کار در باغ دست نمی‌کشید', translit: 'hargez az kār dar bāgh dast nemikeshid', en: 'he never gave up working in the garden' }], grammarConceptIds: ['g-concessive-clauses', 'g-imperfect-past'], vocabIds: ['adj-khaste'], confidence: 'high-confidence' },
  { id: 's-p4-4', fa: 'یک روز، پسر همسایه از او پرسید چرا این‌قدر به این باغ اهمیت می‌دهد.', translit: "yek ruz, pesar-e hamsāye az u porsid cherā in-ghadr be in bāgh ahamiyat midahad.", en: 'One day, the neighbor\'s son asked him why he cared so much about this garden.', literalEn: 'one day, son-of neighbor from him asked why this-much to this garden importance gives', register: 'literary', level: 6, words: [{ fa: 'یک روز، پسر همسایه از او پرسید', translit: 'yek ruz, pesar-e hamsāye az u porsid', en: "one day, the neighbor's son asked him", vocabId: 'fam-pesar' }, { fa: 'چرا این‌قدر به این باغ اهمیت می‌دهد', translit: 'cherā in-ghadr be in bāgh ahamiyat midahad', en: 'why he cared so much about this garden', vocabId: 'q-chera' }], vocabIds: ['fam-pesar', 'q-chera'], confidence: 'high-confidence' },
  { id: 's-p4-5', fa: 'پیرمرد لبخند زد و گفت که این باغ یادگار همسرش است.', translit: "pirmard labkhand zad va goft ke in bāgh yādegār-e hamsarash ast.", en: 'The old man smiled and said that this garden was a keepsake from his wife.', literalEn: 'old-man smile hit and said that this garden keepsake-of his-spouse is', register: 'literary', level: 6, words: [{ fa: 'پیرمرد لبخند زد', translit: 'pirmard labkhand zad', en: 'the old man smiled' }, { fa: 'و گفت که این باغ یادگار همسرش است', translit: 'va goft ke in bāgh yādegār-e hamsarash ast', en: 'and said this garden was a keepsake from his wife' }], grammarConceptIds: ['g-reported-speech'], confidence: 'high-confidence' },
  { id: 's-p4-6', fa: 'چون این باغ خاطرات زیادی برایش داشت، هرگز آن را ترک نمی‌کرد.', translit: "chon in bāgh khāterāt-e ziyādi barāyash dāsht, hargez ān rā tark nemikard.", en: 'Because this garden held many memories for him, he would never leave it.', literalEn: 'because this garden memories-of many for-him had, never it [obj.] departure was-not-doing', register: 'literary', level: 6, words: [{ fa: 'چون این باغ خاطرات زیادی برایش داشت', translit: 'chon in bāgh khāterāt-e ziyādi barāyash dāsht', en: 'because this garden held many memories for him' }, { fa: 'هرگز آن را ترک نمی‌کرد', translit: 'hargez ān rā tark nemikard', en: 'he would never leave it' }], grammarConceptIds: ['g-causal-clauses', 'g-imperfect-past', 'g-object-marker-ra'], confidence: 'high-confidence' },
]
