import type { VocabItem } from '../types'

/** High-frequency conversational expressions that don't translate word for
 *  word — the natural English gloss is what matters, and the literal gloss
 *  is included to show learners how the Persian is actually built. */
export const expressionsVocab: VocabItem[] = [
  { id: 'exp-chekar-mikoni', fa: 'چیکار می‌کنی؟', translit: 'chikār mikoni?', en: "what are you up to? / what are you doing?", pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 1, level: 1, literalEn: 'what-work are you doing?', confidence: 'high-confidence' },
  { id: 'exp-che-khabar', fa: 'چه خبر؟', translit: 'che khabar?', en: "what's up? / what's new?", pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 1, level: 1, literalEn: 'what news?', confidence: 'high-confidence' },
  { id: 'exp-salamati', fa: 'سلامتی', translit: 'salāmati', en: '"to your health" / (casual reply to "what\'s up")', pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 2, level: 1, notes: 'Also a casual, upbeat answer to چه خبر meaning roughly "nothing much, all good".', note: 'The idiomatic "nothing much, all good" usage as a reply to چه خبر is a secondary/derived sense worth a native speaker confirming, alongside the primary toast/"to your health" meaning.', confidence: 'needs-review' },
  { id: 'exp-nooshejan', fa: 'نوش جان', translit: 'nush-e jān', en: 'enjoy your meal / bon appétit', pos: 'phrase', category: 'expressions', register: 'neutral', frequency: 2, level: 1, literalEn: 'may it nourish [your] soul', confidence: 'high-confidence' },
  { id: 'exp-dastodorost', fa: 'دستت درد نکنه', translit: 'dastet dard nakone', en: 'thanks (informal, lit. to someone who did/made something for you)', pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 2, level: 2, literalEn: 'may your hand not hurt', confidence: 'high-confidence' },
  { id: 'exp-khastenabashid', fa: 'خسته نباشید', translit: 'khaste nabāshid', en: 'thanks for your hard work (said to someone working/finishing work)', pos: 'phrase', category: 'expressions', register: 'formal', frequency: 3, level: 2, literalEn: 'may you not be tired', notes: 'A very common Iranian social formula with no single-word English equivalent.', confidence: 'high-confidence' },
  { id: 'exp-ghorboonat', fa: 'قربونت برم', translit: 'ghorbunet beram', en: 'affectionate filler, roughly "you\'re so sweet" / "bless you"', pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 2, level: 2, literalEn: 'may I be sacrificed for you', notes: 'Extremely common term of affection between friends/family, not literal.', note: 'Idiomatic, non-literal expression — worth confirming the exact tone/context range (e.g. whether it reads as too intimate in some relationships) with a native speaker.', confidence: 'needs-review' },
  { id: 'exp-eshkali-nadare', fa: 'اشکالی نداره', translit: 'eshkāli nadāre', en: "it's okay / no problem / never mind", pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'exp-halet-khoobe', fa: 'حالت خوبه؟', translit: 'hālet khube?', en: 'are you okay?', pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'exp-mishe', fa: 'میشه...؟', translit: 'mishe...?', en: 'could you...? / is it possible to...?', pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 1, level: 2, literalEn: 'does it become [possible]...?', notes: 'A very common polite-request opener, e.g. میشه کمکم کنید؟ "could you help me?"', confidence: 'high-confidence' },
  { id: 'exp-albate', fa: 'البته', translit: 'albatte', en: 'of course / certainly', pos: 'adverb', category: 'expressions', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'exp-motmaenam', fa: 'مطمئنم', translit: "motma'enam", en: "I'm sure", pos: 'phrase', category: 'expressions', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'exp-nemidoonam', fa: 'نمی‌دونم', translit: 'nemidunam', en: "I don't know", pos: 'phrase', category: 'expressions', register: 'colloquial', frequency: 1, level: 1, altEn: ['نمی‌دانم (nemidānam) is the formal/written form.'], confidence: 'high-confidence' },
]

export const dailyActivitiesVocab: VocabItem[] = [
  { id: 'daily-bidaar-shodan', fa: 'بیدار شدن', translit: 'bidār shodan', en: 'to wake up', pos: 'verb', category: 'daily-activities', register: 'neutral', frequency: 1, level: 1, isCompoundVerb: true, verbStems: { present: 'بیدار شو', past: 'بیدار شد', presentTranslit: 'bidār sho', pastTranslit: 'bidār shod' }, confidence: 'high-confidence' },
  { id: 'daily-dosh-gereftan', fa: 'دوش گرفتن', translit: 'dush gereftan', en: 'to take a shower', pos: 'verb', category: 'daily-activities', register: 'neutral', frequency: 2, level: 1, isCompoundVerb: true, verbStems: { present: 'دوش گیر', past: 'دوش گرفت', presentTranslit: 'dush gir', pastTranslit: 'dush gereft' }, confidence: 'high-confidence' },
  { id: 'daily-sohbat', fa: 'صبحانه خوردن', translit: 'sobhāne khordan', en: 'to eat breakfast', pos: 'verb', category: 'daily-activities', register: 'neutral', frequency: 2, level: 1, isCompoundVerb: true, verbStems: { present: 'صبحانه خور', past: 'صبحانه خورد', presentTranslit: 'sobhāne khor', pastTranslit: 'sobhāne khord' }, confidence: 'high-confidence' },
  { id: 'daily-varzesh', fa: 'ورزش کردن', translit: 'varzesh kardan', en: 'to exercise', pos: 'verb', category: 'daily-activities', register: 'neutral', frequency: 2, level: 1, isCompoundVerb: true, verbStems: { present: 'ورزش کن', past: 'ورزش کرد', presentTranslit: 'varzesh kon', pastTranslit: 'varzesh kard' }, confidence: 'high-confidence' },
  { id: 'daily-bazi-kardan', fa: 'بازی کردن', translit: 'bāzi kardan', en: 'to play', pos: 'verb', category: 'daily-activities', register: 'neutral', frequency: 2, level: 1, isCompoundVerb: true, verbStems: { present: 'بازی کن', past: 'بازی کرد', presentTranslit: 'bāzi kon', pastTranslit: 'bāzi kard' }, confidence: 'high-confidence' },
  { id: 'daily-guesh-dadan', fa: 'گوش دادن', translit: 'gush dādan', en: 'to listen', pos: 'verb', category: 'daily-activities', register: 'neutral', frequency: 2, level: 1, isCompoundVerb: true, verbStems: { present: 'گوش ده', past: 'گوش داد', presentTranslit: 'gush deh', pastTranslit: 'gush dād' }, confidence: 'high-confidence' },
  { id: 'daily-negah-kardan', fa: 'نگاه کردن', translit: 'negāh kardan', en: 'to look (at) / to watch', pos: 'verb', category: 'daily-activities', register: 'neutral', frequency: 1, level: 1, isCompoundVerb: true, verbStems: { present: 'نگاه کن', past: 'نگاه کرد', presentTranslit: 'negāh kon', pastTranslit: 'negāh kard' }, confidence: 'high-confidence' },
]
