import type { VocabItem } from '../types'

export const travelVocab: VocabItem[] = [
  { id: 'trav-havapeyma', fa: 'هواپیما', translit: 'havāpeymā', en: 'airplane', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'trav-forudgah', fa: 'فرودگاه', translit: 'forudgāh', en: 'airport', pos: 'noun', category: 'travel', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'trav-ghatar', fa: 'قطار', translit: 'qatār', en: 'train', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'trav-otobus', fa: 'اتوبوس', translit: 'otobus', en: 'bus', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'trav-taxi', fa: 'تاکسی', translit: 'tāxi', en: 'taxi', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'trav-mashin', fa: 'ماشین', translit: 'māshin', en: 'car', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'trav-bilit', fa: 'بلیت', translit: 'belit', en: 'ticket', pos: 'noun', category: 'travel', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'trav-safar', fa: 'سفر', translit: 'safar', en: 'trip / journey', pos: 'noun', category: 'travel', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'trav-hotel', fa: 'هتل', translit: 'hotel', en: 'hotel', pos: 'noun', category: 'travel', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'trav-passport', fa: 'پاسپورت', translit: 'pāsport', en: 'passport', pos: 'noun', category: 'travel', register: 'neutral', frequency: 3, level: 1, altEn: ['گذرنامه (gozarnāme) is the formal/official Persian term.'], confidence: 'high-confidence' },
  { id: 'trav-chamedan', fa: 'چمدان', translit: 'chamedān', en: 'suitcase', pos: 'noun', category: 'travel', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'trav-viza', fa: 'ویزا', translit: 'vizā', en: 'visa', pos: 'noun', category: 'travel', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'trav-naghshe', fa: 'نقشه', translit: 'naghshe', en: 'map', pos: 'noun', category: 'travel', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'trav-docharkhe', fa: 'دوچرخه', translit: 'docharkhe', en: 'bicycle', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'trav-motorsiklet', fa: 'موتورسیکلت', translit: 'motorsiklet', en: 'motorcycle', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 3, level: 1, altEn: ['موتور (motor) is the common everyday shortening.'], confidence: 'verified' },
  { id: 'trav-metro', fa: 'مترو', translit: 'metro', en: 'metro / subway', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'trav-ranande', fa: 'راننده', translit: 'rānande', en: 'driver', pos: 'noun', category: 'transportation', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'dir-rast', fa: 'راست', translit: 'rāst', en: 'right (direction)', pos: 'adverb', category: 'directions', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'dir-chap', fa: 'چپ', translit: 'chap', en: 'left (direction)', pos: 'adverb', category: 'directions', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'dir-mostaghim', fa: 'مستقیم', translit: 'mostaqim', en: 'straight ahead', pos: 'adverb', category: 'directions', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'dir-nazdik', fa: 'نزدیک', translit: 'nazdik', en: 'near / close', pos: 'adjective', category: 'directions', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'dir-dur', fa: 'دور', translit: 'dur', en: 'far', pos: 'adjective', category: 'directions', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'dir-khiaban', fa: 'خیابان', translit: 'khiābān', en: 'street', pos: 'noun', category: 'directions', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'dir-shomal', fa: 'شمال', translit: 'shomāl', en: 'north', pos: 'noun', category: 'directions', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'dir-jonub', fa: 'جنوب', translit: 'jonub', en: 'south', pos: 'noun', category: 'directions', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'dir-shargh', fa: 'شرق', translit: 'shargh', en: 'east', pos: 'noun', category: 'directions', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
  { id: 'dir-gharb', fa: 'غرب', translit: 'gharb', en: 'west', pos: 'noun', category: 'directions', register: 'neutral', frequency: 2, level: 1, confidence: 'verified' },
]

export const housingVocab: VocabItem[] = [
  { id: 'home-khane', fa: 'خانه', translit: 'khāne', en: 'house / home', pos: 'noun', category: 'housing', register: 'neutral', frequency: 1, level: 1, altEn: ['خونه (khune) is the everyday spoken pronunciation.'], confidence: 'high-confidence' },
  { id: 'home-apartman', fa: 'آپارتمان', translit: 'āpārtemān', en: 'apartment', pos: 'noun', category: 'housing', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'home-otagh', fa: 'اتاق', translit: 'otāq', en: 'room', pos: 'noun', category: 'housing', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'home-otaghkhab', fa: 'اتاق خواب', translit: 'otāq-e khāb', en: 'bedroom', pos: 'noun', category: 'housing', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'home-ashpazkhane', fa: 'آشپزخانه', translit: 'āshpazkhāne', en: 'kitchen', pos: 'noun', category: 'housing', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'home-dar', fa: 'در', translit: 'dar', en: 'door', pos: 'noun', category: 'housing', register: 'neutral', frequency: 1, level: 1, confidence: 'high-confidence' },
  { id: 'home-panjere', fa: 'پنجره', translit: 'panjere', en: 'window', pos: 'noun', category: 'housing', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'home-miz', fa: 'میز', translit: 'miz', en: 'table', pos: 'noun', category: 'housing', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'home-sandali', fa: 'صندلی', translit: 'sandali', en: 'chair', pos: 'noun', category: 'housing', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
  { id: 'home-takht', fa: 'تخت', translit: 'takht', en: 'bed', pos: 'noun', category: 'housing', register: 'neutral', frequency: 2, level: 1, confidence: 'high-confidence' },
]
