import type { VocabItem } from '../types'

/**
 * Core verbs, cited by their infinitive (masdar). Persian conjugation is
 * built entirely from two stems per verb — present and past — which are
 * often not predictable from each other, so both are recorded explicitly
 * here rather than derived. This is the data the grammar engine (present
 * tense, past tense, subjunctive, imperative units) points back to.
 *
 * می‌ (mi-) + present stem + person ending = present tense (می‌روم = I go).
 * past stem + person ending = simple past (رفتم = I went).
 */
export const verbsCoreVocab: VocabItem[] = [
  { id: 'verb-budan', fa: 'بودن', translit: 'budan', en: 'to be', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'ه/است', past: 'بود', presentTranslit: '(copula: -am/-i/-ast...)', pastTranslit: 'bud' },
    notes: 'Irregular: the present tense of "to be" uses copula endings (هستم، هستی، است...) rather than می‌ + stem.',
    confidence: 'high-confidence' },
  { id: 'verb-dashtan', fa: 'داشتن', translit: 'dāshtan', en: 'to have', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'دار', past: 'داشت', presentTranslit: 'dār', pastTranslit: 'dāsht' },
    notes: 'Unlike most verbs, the present tense of داشتن normally drops the می‌ prefix: دارم not می‌دارم.',
    confidence: 'high-confidence' },
  { id: 'verb-raftan', fa: 'رفتن', translit: 'raftan', en: 'to go', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'رو', past: 'رفت', presentTranslit: 'rav', pastTranslit: 'raft' }, confidence: 'high-confidence' },
  { id: 'verb-amadan', fa: 'آمدن', translit: 'āmadan', en: 'to come', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'آی', past: 'آمد', presentTranslit: 'āy', pastTranslit: 'āmad' }, confidence: 'high-confidence' },
  { id: 'verb-khordan', fa: 'خوردن', translit: 'khordan', en: 'to eat / to drink', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'خور', past: 'خورد', presentTranslit: 'khor', pastTranslit: 'khord' },
    notes: 'Used for drinking too: آب خوردن "to drink water" (not "eat").', confidence: 'high-confidence' },
  { id: 'verb-didan', fa: 'دیدن', translit: 'didan', en: 'to see', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'بین', past: 'دید', presentTranslit: 'bin', pastTranslit: 'did' }, confidence: 'high-confidence' },
  { id: 'verb-goftan', fa: 'گفتن', translit: 'goftan', en: 'to say / to tell', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'گو', past: 'گفت', presentTranslit: 'gu', pastTranslit: 'goft' }, confidence: 'high-confidence' },
  { id: 'verb-kardan', fa: 'کردن', translit: 'kardan', en: 'to do / to make', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'کن', past: 'کرد', presentTranslit: 'kon', pastTranslit: 'kard' },
    notes: 'The single most important verb in Persian: it combines with nouns to form most compound (light) verbs, e.g. کار کردن "to work", صحبت کردن "to talk".',
    confidence: 'high-confidence' },
  { id: 'verb-khastan', fa: 'خواستن', translit: 'khāstan', en: 'to want', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'خواه', past: 'خواست', presentTranslit: 'khāh', pastTranslit: 'khāst' },
    notes: 'Colloquial present stem is often خوا (khā), e.g. می‌خوام (mikhām) instead of formal می‌خواهم (mikhāham).',
    confidence: 'high-confidence' },
  { id: 'verb-tavanestan', fa: 'توانستن', translit: 'tavānestan', en: 'to be able to / can', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 2,
    verbStems: { present: 'توان', past: 'توانست', presentTranslit: 'tavān', pastTranslit: 'tavānest' },
    notes: 'Colloquial: می‌تونم (mitunam) instead of formal می‌توانم (mitavānam).', confidence: 'high-confidence' },
  { id: 'verb-dadan', fa: 'دادن', translit: 'dādan', en: 'to give', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'ده', past: 'داد', presentTranslit: 'deh', pastTranslit: 'dād' }, confidence: 'high-confidence' },
  { id: 'verb-gereftan', fa: 'گرفتن', translit: 'gereftan', en: 'to take / to get', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'گیر', past: 'گرفت', presentTranslit: 'gir', pastTranslit: 'gereft' }, confidence: 'high-confidence' },
  { id: 'verb-shodan', fa: 'شدن', translit: 'shodan', en: 'to become', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 2,
    verbStems: { present: 'شو', past: 'شد', presentTranslit: 'sho', pastTranslit: 'shod' },
    notes: 'Also the passive-voice helper verb: نوشته شد "it was written".', confidence: 'high-confidence' },
  { id: 'verb-khandan', fa: 'خواندن', translit: 'khāndan', en: 'to read / to call / to sing', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'خوان', past: 'خواند', presentTranslit: 'khān', pastTranslit: 'khānd' },
    notes: 'Colloquial present stem خون (khun): می‌خونم (mikhunam).', confidence: 'high-confidence' },
  { id: 'verb-neveshtan', fa: 'نوشتن', translit: 'neveshtan', en: 'to write', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'نویس', past: 'نوشت', presentTranslit: 'nevis', pastTranslit: 'nevesht' }, confidence: 'high-confidence' },
  { id: 'verb-khabidan', fa: 'خوابیدن', translit: 'khābidan', en: 'to sleep', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'خواب', past: 'خوابید', presentTranslit: 'khāb', pastTranslit: 'khābid' }, confidence: 'high-confidence' },
  { id: 'verb-fahmidan', fa: 'فهمیدن', translit: 'fahmidan', en: 'to understand', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 2,
    verbStems: { present: 'فهم', past: 'فهمید', presentTranslit: 'fahm', pastTranslit: 'fahmid' }, confidence: 'high-confidence' },
  { id: 'verb-shenidan', fa: 'شنیدن', translit: 'shenidan', en: 'to hear', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 2, level: 2,
    verbStems: { present: 'شنو', past: 'شنید', presentTranslit: 'shenow', pastTranslit: 'shenid' }, confidence: 'high-confidence' },
  { id: 'verb-kharidan', fa: 'خریدن', translit: 'kharidan', en: 'to buy', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    verbStems: { present: 'خر', past: 'خرید', presentTranslit: 'khar', pastTranslit: 'kharid' }, confidence: 'high-confidence' },
  { id: 'verb-mandan', fa: 'ماندن', translit: 'māndan', en: 'to stay / to remain', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 2, level: 2,
    verbStems: { present: 'مان', past: 'ماند', presentTranslit: 'mān', pastTranslit: 'mānd' }, confidence: 'high-confidence' },
  { id: 'verb-residan', fa: 'رسیدن', translit: 'residan', en: 'to arrive', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 2, level: 2,
    verbStems: { present: 'رس', past: 'رسید', presentTranslit: 'res', pastTranslit: 'resid' }, confidence: 'high-confidence' },
  { id: 'verb-zadan', fa: 'زدن', translit: 'zadan', en: 'to hit / to strike', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 2, level: 2,
    verbStems: { present: 'زن', past: 'زد', presentTranslit: 'zan', pastTranslit: 'zad' },
    notes: 'Very productive in compounds: حرف زدن "to speak", زنگ زدن "to call (phone)".', confidence: 'high-confidence' },
  { id: 'verb-kar-kardan', fa: 'کار کردن', translit: 'kār kardan', en: 'to work', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    isCompoundVerb: true, verbStems: { present: 'کار کن', past: 'کار کرد', presentTranslit: 'kār kon', pastTranslit: 'kār kard' }, confidence: 'high-confidence' },
  { id: 'verb-sohbat-kardan', fa: 'صحبت کردن', translit: 'sohbat kardan', en: 'to talk / to speak', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    isCompoundVerb: true, verbStems: { present: 'صحبت کن', past: 'صحبت کرد', presentTranslit: 'sohbat kon', pastTranslit: 'sohbat kard' }, confidence: 'high-confidence' },
  { id: 'verb-dust-dashtan', fa: 'دوست داشتن', translit: 'dust dāshtan', en: 'to like / to love', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 1, level: 1,
    isCompoundVerb: true, verbStems: { present: 'دوست دار', past: 'دوست داشت', presentTranslit: 'dust dār', pastTranslit: 'dust dāsht' }, confidence: 'high-confidence' },
  { id: 'verb-dars-khandan', fa: 'درس خواندن', translit: 'dars khāndan', en: 'to study', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 2, level: 1,
    isCompoundVerb: true, verbStems: { present: 'درس خوان', past: 'درس خواند', presentTranslit: 'dars khān', pastTranslit: 'dars khānd' }, confidence: 'high-confidence' },
  { id: 'verb-zendegi-kardan', fa: 'زندگی کردن', translit: 'zendegi kardan', en: 'to live', pos: 'verb', category: 'verbs-core', register: 'neutral', frequency: 2, level: 2,
    isCompoundVerb: true, verbStems: { present: 'زندگی کن', past: 'زندگی کرد', presentTranslit: 'zendegi kon', pastTranslit: 'zendegi kard' }, confidence: 'high-confidence' },
]
