import type { AlphabetLetter, PersianDigit, ShortVowel } from './types'

/**
 * The Persian alphabet: 32 letters, written right-to-left, cursive
 * (most letters connect to their neighbors). It is the Arabic script plus
 * four Persian-specific letters (پ چ ژ گ) for sounds Arabic doesn't have.
 *
 * `forms` uses a tatweel (ـ, U+0640) joined to the base letter to *display*
 * how each form looks in context, rather than separate Unicode
 * presentation-form codepoints — this is the standard textbook convention
 * and renders correctly with normal Arabic-script text shaping.
 *
 * Six letters (ا د ذ ر ز ژ و) never connect to the letter that follows them.
 * For those, `forms.initial === forms.isolated` and `forms.medial ===
 * forms.final`, and `joinsNext` is false.
 *
 * Order follows standard Persian dictionary order (the order used in every
 * Persian dictionary and by virtually all textbooks), which doubles as a
 * perfectly reasonable teaching order.
 */
export const alphabet: AlphabetLetter[] = [
  {
    id: 'alef', order: 1, name: 'Alef', nameFa: 'الف',
    forms: { isolated: 'ا', initial: 'ا', medial: 'ـا', final: 'ـا' },
    joinsNext: false, transliteration: 'ā / a',
    soundDescription: 'At the start of a word, alef is a seat for a short "a" sound or a glottal stop before a vowel. Elsewhere, ا represents the long vowel "ā" (like "a" in "father"). With a hat, آ is always the long "ā" sound.',
    englishSoundHint: 'the "a" in "father", held long',
    exampleWords: [
      { fa: 'آب', translit: 'āb', en: 'water' },
      { fa: 'ایران', translit: 'irān', en: 'Iran' },
    ],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'be', order: 2, name: 'Be', nameFa: 'به',
    forms: { isolated: 'ب', initial: 'بـ', medial: 'ـبـ', final: 'ـب' },
    joinsNext: true, transliteration: 'b',
    soundDescription: 'Like English "b" in "bed".',
    englishSoundHint: '"b" as in "bed"',
    exampleWords: [{ fa: 'باد', translit: 'bād', en: 'wind' }, { fa: 'کتاب', translit: 'ketāb', en: 'book' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'pe', order: 3, name: 'Pe', nameFa: 'په',
    forms: { isolated: 'پ', initial: 'پـ', medial: 'ـپـ', final: 'ـپ' },
    joinsNext: true, transliteration: 'p',
    soundDescription: 'Like English "p" in "pen". Not present in Arabic — one of four Persian-specific letters.',
    englishSoundHint: '"p" as in "pen"',
    oftenConfusedWith: ['be', 'te', 'the'],
    exampleWords: [{ fa: 'پدر', translit: 'pedar', en: 'father' }, { fa: 'پول', translit: 'pul', en: 'money' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'te', order: 4, name: 'Te', nameFa: 'ته',
    forms: { isolated: 'ت', initial: 'تـ', medial: 'ـتـ', final: 'ـت' },
    joinsNext: true, transliteration: 't',
    soundDescription: 'Like English "t" in "top".',
    englishSoundHint: '"t" as in "top"',
    oftenConfusedWith: ['be', 'pe', 'the'],
    exampleWords: [{ fa: 'تو', translit: 'to', en: 'you (informal)' }, { fa: 'دست', translit: 'dast', en: 'hand' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'the', order: 5, name: 'Se', nameFa: 'ثه',
    forms: { isolated: 'ث', initial: 'ثـ', medial: 'ـثـ', final: 'ـث' },
    joinsNext: true, transliteration: 's',
    soundDescription: 'Pronounced exactly like س (s) in Persian — the distinct Arabic "th" sound is not used. Appears mainly in words borrowed from Arabic.',
    englishSoundHint: '"s" as in "sun"',
    oftenConfusedWith: ['be', 'pe', 'te'],
    exampleWords: [{ fa: 'مثال', translit: 'mesāl', en: 'example' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'jim', order: 6, name: 'Jim', nameFa: 'جیم',
    forms: { isolated: 'ج', initial: 'جـ', medial: 'ـجـ', final: 'ـج' },
    joinsNext: true, transliteration: 'j',
    soundDescription: 'Like English "j" in "jam".',
    englishSoundHint: '"j" as in "jam"',
    oftenConfusedWith: ['che', 'he_jimi', 'khe'],
    exampleWords: [{ fa: 'جان', translit: 'jān', en: 'life / dear (term of endearment)' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'che', order: 7, name: 'Che', nameFa: 'چه',
    forms: { isolated: 'چ', initial: 'چـ', medial: 'ـچـ', final: 'ـچ' },
    joinsNext: true, transliteration: 'ch',
    soundDescription: 'Like English "ch" in "chair". A Persian-specific letter.',
    englishSoundHint: '"ch" as in "chair"',
    oftenConfusedWith: ['jim', 'he_jimi', 'khe'],
    exampleWords: [{ fa: 'چای', translit: 'chāy', en: 'tea' }, { fa: 'چرا', translit: 'cherā', en: 'why' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'he_jimi', order: 8, name: 'He (jimi)', nameFa: 'حه',
    forms: { isolated: 'ح', initial: 'حـ', medial: 'ـحـ', final: 'ـح' },
    joinsNext: true, transliteration: 'h',
    soundDescription: 'Pronounced identically to ه (he) in Persian — a plain "h" sound. Historically a distinct Arabic sound; Persian collapsed the distinction. Mostly in Arabic loanwords.',
    englishSoundHint: '"h" as in "hat"',
    oftenConfusedWith: ['jim', 'che', 'khe', 'he_docheshm'],
    exampleWords: [{ fa: 'حال', translit: 'hāl', en: 'condition / feeling' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'khe', order: 9, name: 'Khe', nameFa: 'خه',
    forms: { isolated: 'خ', initial: 'خـ', medial: 'ـخـ', final: 'ـخ' },
    joinsNext: true, transliteration: 'kh',
    soundDescription: 'A raspy sound made at the back of the throat, like the "ch" in Scottish "loch" or German "Bach". Not found in standard English.',
    englishSoundHint: 'like the "ch" in Scottish "loch"',
    oftenConfusedWith: ['jim', 'che', 'he_jimi'],
    exampleWords: [{ fa: 'خانه', translit: 'khāne', en: 'house' }, { fa: 'خوب', translit: 'khub', en: 'good' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'dal', order: 10, name: 'Dal', nameFa: 'دال',
    forms: { isolated: 'د', initial: 'د', medial: 'ـد', final: 'ـد' },
    joinsNext: false, transliteration: 'd',
    soundDescription: 'Like English "d" in "day". Never connects to the next letter.',
    englishSoundHint: '"d" as in "day"',
    oftenConfusedWith: ['zal'],
    exampleWords: [{ fa: 'در', translit: 'dar', en: 'door / in' }, { fa: 'مادر', translit: 'mādar', en: 'mother' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'zal', order: 11, name: 'Zal', nameFa: 'ذال',
    forms: { isolated: 'ذ', initial: 'ذ', medial: 'ـذ', final: 'ـذ' },
    joinsNext: false, transliteration: 'z',
    soundDescription: 'Pronounced exactly like ز (z) in Persian. Appears in Arabic loanwords. Never connects to the next letter.',
    englishSoundHint: '"z" as in "zoo"',
    oftenConfusedWith: ['dal', 'ze', 'zhe'],
    exampleWords: [{ fa: 'لذت', translit: 'lezzat', en: 'enjoyment, pleasure' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 're', order: 12, name: 'Re', nameFa: 'ره',
    forms: { isolated: 'ر', initial: 'ر', medial: 'ـر', final: 'ـر' },
    joinsNext: false, transliteration: 'r',
    soundDescription: 'A flapped/trilled "r", closer to Spanish "r" than the English one. Never connects to the next letter.',
    englishSoundHint: 'a flapped "r", like Spanish "pero"',
    oftenConfusedWith: ['ze', 'zhe'],
    exampleWords: [{ fa: 'ایران', translit: 'irān', en: 'Iran' }, { fa: 'دختر', translit: 'dokhtar', en: 'daughter/girl' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'ze', order: 13, name: 'Ze', nameFa: 'زه',
    forms: { isolated: 'ز', initial: 'ز', medial: 'ـز', final: 'ـز' },
    joinsNext: false, transliteration: 'z',
    soundDescription: 'Like English "z" in "zoo". Never connects to the next letter.',
    englishSoundHint: '"z" as in "zoo"',
    oftenConfusedWith: ['re', 'zhe', 'zal'],
    exampleWords: [{ fa: 'زن', translit: 'zan', en: 'woman' }, { fa: 'روز', translit: 'ruz', en: 'day' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'zhe', order: 14, name: 'Zhe', nameFa: 'ژه',
    forms: { isolated: 'ژ', initial: 'ژ', medial: 'ـژ', final: 'ـژ' },
    joinsNext: false, transliteration: 'zh',
    soundDescription: 'Like the "s" in "treasure" or the French "j" in "Jacques". A Persian-specific letter; fairly rare. Never connects to the next letter.',
    englishSoundHint: '"s" as in "treasure"',
    oftenConfusedWith: ['re', 'ze'],
    exampleWords: [{ fa: 'ژاپن', translit: 'zhāpon', en: 'Japan' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'sin', order: 15, name: 'Sin', nameFa: 'سین',
    forms: { isolated: 'س', initial: 'سـ', medial: 'ـسـ', final: 'ـس' },
    joinsNext: true, transliteration: 's',
    soundDescription: 'Like English "s" in "sun".',
    englishSoundHint: '"s" as in "sun"',
    oftenConfusedWith: ['shin', 'sad'],
    exampleWords: [{ fa: 'سلام', translit: 'salām', en: 'hello' }, { fa: 'اسم', translit: 'esm', en: 'name' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'shin', order: 16, name: 'Shin', nameFa: 'شین',
    forms: { isolated: 'ش', initial: 'شـ', medial: 'ـشـ', final: 'ـش' },
    joinsNext: true, transliteration: 'sh',
    soundDescription: 'Like English "sh" in "shoe".',
    englishSoundHint: '"sh" as in "shoe"',
    oftenConfusedWith: ['sin'],
    exampleWords: [{ fa: 'شب', translit: 'shab', en: 'night' }, { fa: 'دانشجو', translit: 'dāneshju', en: 'university student' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'sad', order: 17, name: 'Sad', nameFa: 'صاد',
    forms: { isolated: 'ص', initial: 'صـ', medial: 'ـصـ', final: 'ـص' },
    joinsNext: true, transliteration: 's',
    soundDescription: 'Pronounced exactly like س (s) in Persian. Appears in Arabic loanwords.',
    englishSoundHint: '"s" as in "sun"',
    oftenConfusedWith: ['sin', 'zad'],
    exampleWords: [{ fa: 'صبح', translit: 'sobh', en: 'morning' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'zad', order: 18, name: 'Zad', nameFa: 'ضاد',
    forms: { isolated: 'ض', initial: 'ضـ', medial: 'ـضـ', final: 'ـض' },
    joinsNext: true, transliteration: 'z',
    soundDescription: 'Pronounced exactly like ز (z) in Persian. Appears in Arabic loanwords.',
    englishSoundHint: '"z" as in "zoo"',
    oftenConfusedWith: ['sad', 'ze'],
    exampleWords: [{ fa: 'ریاضی', translit: 'riyāzi', en: 'mathematics' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'ta_arabic', order: 19, name: 'Ta', nameFa: 'طا',
    forms: { isolated: 'ط', initial: 'طـ', medial: 'ـطـ', final: 'ـط' },
    joinsNext: true, transliteration: 't',
    soundDescription: 'Pronounced exactly like ت (t) in Persian. Appears in Arabic loanwords.',
    englishSoundHint: '"t" as in "top"',
    oftenConfusedWith: ['te'],
    exampleWords: [{ fa: 'طبیعت', translit: 'tabiat', en: 'nature' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'za_arabic', order: 20, name: 'Za', nameFa: 'ظا',
    forms: { isolated: 'ظ', initial: 'ظـ', medial: 'ـظـ', final: 'ـظ' },
    joinsNext: true, transliteration: 'z',
    soundDescription: 'Pronounced exactly like ز (z) in Persian. Appears in Arabic loanwords; relatively rare.',
    englishSoundHint: '"z" as in "zoo"',
    oftenConfusedWith: ['zad', 'ze'],
    exampleWords: [{ fa: 'ظهر', translit: 'zohr', en: 'noon' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'eyn', order: 21, name: 'Eyn', nameFa: 'عین',
    forms: { isolated: 'ع', initial: 'عـ', medial: 'ـعـ', final: 'ـع' },
    joinsNext: true, transliteration: "'",
    soundDescription: 'A glottal stop (the catch in your throat in "uh-oh") in most positions, sometimes nearly silent between vowels. One of the trickier letters for English speakers; it is not a vowel itself but often sits next to one.',
    englishSoundHint: 'the catch in "uh-oh"',
    exampleWords: [{ fa: 'بعد', translit: "ba'd", en: 'after' }, { fa: 'ساعت', translit: "sā'at", en: 'hour / clock' }],
    category: 'consonant', confidence: 'verified', note: 'Confirmed against Persian Language Online (persianlanguageonline.com/alphabet/ain) and general Persian phonology references: in modern (Iranian) Persian ع is realized as a glottal stop or brief glottal constriction, unlike the pharyngeal consonant of Arabic — the beginner-level "catch in uh-oh" description matches the standard characterization, though exact realization does vary by position/dialect as noted.',
  },
  {
    id: 'gheyn', order: 22, name: 'Gheyn', nameFa: 'غین',
    forms: { isolated: 'غ', initial: 'غـ', medial: 'ـغـ', final: 'ـغ' },
    joinsNext: true, transliteration: 'gh',
    soundDescription: 'A voiced sound made in the back of the throat, similar to a French/German "r". In modern Persian it sounds the same as ق (qaf).',
    englishSoundHint: 'like a French "r", but voiced and raspy',
    oftenConfusedWith: ['qaf', 'khe'],
    exampleWords: [{ fa: 'غذا', translit: 'ghazā', en: 'food' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'fe', order: 23, name: 'Fe', nameFa: 'فه',
    forms: { isolated: 'ف', initial: 'فـ', medial: 'ـفـ', final: 'ـف' },
    joinsNext: true, transliteration: 'f',
    soundDescription: 'Like English "f" in "fun".',
    englishSoundHint: '"f" as in "fun"',
    exampleWords: [{ fa: 'فارسی', translit: 'fārsi', en: 'Persian (language)' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'qaf', order: 24, name: 'Qaf', nameFa: 'قاف',
    forms: { isolated: 'ق', initial: 'قـ', medial: 'ـقـ', final: 'ـق' },
    joinsNext: true, transliteration: 'q',
    soundDescription: 'In modern Persian this sounds identical to غ (gheyn) — a voiced back-of-the-throat sound. Transliterated "q" by convention to show which letter is written, even though it does not sound like an English "q".',
    englishSoundHint: 'like a French "r", but voiced and raspy (same sound as غ)',
    oftenConfusedWith: ['gheyn'],
    exampleWords: [{ fa: 'قند', translit: 'qand', en: 'sugar cube' }, { fa: 'اتاق', translit: 'otāq', en: 'room' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'kaf', order: 25, name: 'Kaf', nameFa: 'کاف',
    forms: { isolated: 'ک', initial: 'کـ', medial: 'ـکـ', final: 'ـک' },
    joinsNext: true, transliteration: 'k',
    soundDescription: 'Like English "k" in "kite".',
    englishSoundHint: '"k" as in "kite"',
    oftenConfusedWith: ['gaf'],
    exampleWords: [{ fa: 'کتاب', translit: 'ketāb', en: 'book' }, { fa: 'کجا', translit: 'kojā', en: 'where' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'gaf', order: 26, name: 'Gaf', nameFa: 'گاف',
    forms: { isolated: 'گ', initial: 'گـ', medial: 'ـگـ', final: 'ـگ' },
    joinsNext: true, transliteration: 'g',
    soundDescription: 'Like English "g" in "go". A Persian-specific letter.',
    englishSoundHint: '"g" as in "go"',
    oftenConfusedWith: ['kaf'],
    exampleWords: [{ fa: 'گل', translit: 'gol', en: 'flower' }, { fa: 'بزرگ', translit: 'bozorg', en: 'big' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'lam', order: 27, name: 'Lam', nameFa: 'لام',
    forms: { isolated: 'ل', initial: 'لـ', medial: 'ـلـ', final: 'ـل' },
    joinsNext: true, transliteration: 'l',
    soundDescription: 'Like English "l" in "light".',
    englishSoundHint: '"l" as in "light"',
    exampleWords: [{ fa: 'دل', translit: 'del', en: 'heart' }, { fa: 'سال', translit: 'sāl', en: 'year' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'mim', order: 28, name: 'Mim', nameFa: 'میم',
    forms: { isolated: 'م', initial: 'مـ', medial: 'ـمـ', final: 'ـم' },
    joinsNext: true, transliteration: 'm',
    soundDescription: 'Like English "m" in "moon".',
    englishSoundHint: '"m" as in "moon"',
    exampleWords: [{ fa: 'من', translit: 'man', en: 'I / me' }, { fa: 'مادر', translit: 'mādar', en: 'mother' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'nun', order: 29, name: 'Nun', nameFa: 'نون',
    forms: { isolated: 'ن', initial: 'نـ', medial: 'ـنـ', final: 'ـن' },
    joinsNext: true, transliteration: 'n',
    soundDescription: 'Like English "n" in "no".',
    englishSoundHint: '"n" as in "no"',
    exampleWords: [{ fa: 'نان', translit: 'nān', en: 'bread' }, { fa: 'من', translit: 'man', en: 'I / me' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'vav', order: 30, name: 'Vav', nameFa: 'واو',
    forms: { isolated: 'و', initial: 'و', medial: 'ـو', final: 'ـو' },
    joinsNext: false, transliteration: 'v / u / o / ow',
    soundDescription: 'Multi-purpose letter: as a consonant it is "v" (like "van"); as a long vowel it is "u" (like "moon"); in a few common words it represents short "o"; and in the diphthong ـَو it is "ow" (like "know"). Never connects to the next letter.',
    englishSoundHint: '"v" as in "van", or long "oo" as in "moon"',
    exampleWords: [{ fa: 'دو', translit: 'do', en: 'two' }, { fa: 'او', translit: 'u', en: 'he/she' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'he_docheshm', order: 31, name: 'He', nameFa: 'هه',
    forms: { isolated: 'ه', initial: 'هـ', medial: 'ـهـ', final: 'ـه' },
    joinsNext: true, transliteration: 'h / e',
    soundDescription: 'Pronounced identically to ح (he-ye jimi) as "h". At the end of many native Persian words (e.g. خانه) it marks a final short "e" sound rather than a consonant "h".',
    englishSoundHint: '"h" as in "hat"; word-final, often silent-ish "e"',
    oftenConfusedWith: ['he_jimi'],
    exampleWords: [{ fa: 'هفت', translit: 'haft', en: 'seven' }, { fa: 'خانه', translit: 'khāne', en: 'house' }],
    category: 'consonant', confidence: 'high-confidence',
  },
  {
    id: 'ye', order: 32, name: 'Ye', nameFa: 'یه',
    forms: { isolated: 'ی', initial: 'یـ', medial: 'ـیـ', final: 'ـی' },
    joinsNext: true, transliteration: 'y / i / ey',
    soundDescription: 'As a consonant, "y" (like "yes"). As a long vowel, "i" (like "machine"). In the diphthong ـَی it is "ey" (like "hey"). Also used as the "ezāfe-ye" marker after words ending in a vowel.',
    englishSoundHint: '"y" as in "yes", or long "ee" as in "machine"',
    exampleWords: [{ fa: 'یک', translit: 'yek', en: 'one' }, { fa: 'ایران', translit: 'irān', en: 'Iran' }],
    category: 'consonant', confidence: 'high-confidence',
  },
]

export const shortVowels: ShortVowel[] = [
  {
    id: 'zebar', name: 'Zebar (Fatha)', diacritic: 'َ', transliteration: 'a',
    soundDescription: 'A short "a" as in "cat". Written above a letter; in ordinary writing it is almost always left out and inferred from context.',
    exampleWords: [{ fa: 'دَر', translit: 'dar', en: 'door / in' }],
    confidence: 'high-confidence',
  },
  {
    id: 'zir', name: 'Zir (Kasra)', diacritic: 'ِ', transliteration: 'e',
    soundDescription: 'A short "e" as in "bed" (in Persian, unlike Arabic, not "i"). Written below a letter; usually omitted in ordinary writing.',
    exampleWords: [{ fa: 'دِل', translit: 'del', en: 'heart' }],
    confidence: 'high-confidence',
  },
  {
    id: 'pish', name: 'Pish (Damma)', diacritic: 'ُ', transliteration: 'o',
    soundDescription: 'A short "o" as in "hot" (in Persian, unlike Arabic, not "u"). Written above a letter; usually omitted in ordinary writing.',
    exampleWords: [{ fa: 'گُل', translit: 'gol', en: 'flower' }],
    confidence: 'high-confidence',
  },
]

export const persianDigits: PersianDigit[] = [
  { digit: '0', arabicIndicDigit: '۰', name: 'zero', nameFa: 'صفر', transliteration: 'sefr' },
  { digit: '1', arabicIndicDigit: '۱', name: 'one', nameFa: 'یک', transliteration: 'yek' },
  { digit: '2', arabicIndicDigit: '۲', name: 'two', nameFa: 'دو', transliteration: 'do' },
  { digit: '3', arabicIndicDigit: '۳', name: 'three', nameFa: 'سه', transliteration: 'se' },
  { digit: '4', arabicIndicDigit: '۴', name: 'four', nameFa: 'چهار', transliteration: 'chahār' },
  { digit: '5', arabicIndicDigit: '۵', name: 'five', nameFa: 'پنج', transliteration: 'panj' },
  { digit: '6', arabicIndicDigit: '۶', name: 'six', nameFa: 'شش', transliteration: 'shesh' },
  { digit: '7', arabicIndicDigit: '۷', name: 'seven', nameFa: 'هفت', transliteration: 'haft' },
  { digit: '8', arabicIndicDigit: '۸', name: 'eight', nameFa: 'هشت', transliteration: 'hasht' },
  { digit: '9', arabicIndicDigit: '۹', name: 'nine', nameFa: 'نه', transliteration: 'noh' },
]

export function findLetter(id: string): AlphabetLetter | undefined {
  return alphabet.find((l) => l.id === id)
}
