#!/usr/bin/env python3
"""
Pre-generates offline Persian pronunciation audio for the app's content
using edge-tts (Microsoft's free, no-API-key neural TTS — same engine
behind Edge's "Read aloud"). This exists because the app previously relied
solely on the browser's Web Speech API, whose Persian voice availability is
inconsistent across OS/browser combinations — many learners got no audio at
all. Pre-generating real audio files removes that dependency: the clips
ship with the app and always play, on any device.

Still explicitly computer-generated/approximate (not a native-speaker
recording) — the UI labels it as such, honestly, same as before.

Requires ffmpeg on PATH (`brew install ffmpeg` / `apt install ffmpeg`) —
edge-tts's raw output is re-encoded into a standard, well-headered MP3 for
broad playback compatibility (see reencode_for_compatibility below).

Usage:
    npx tsx scripts/collect-audio-text.ts > scripts/.audio-texts.json
    python3 scripts/generate_audio.py

Idempotent/resumable: skips any text whose audio file already exists in
public/audio/, so re-running after adding new content only synthesizes the
new strings. Writes src/content/audioManifest.ts mapping every known text
to its audio file path.
"""
import asyncio
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import edge_tts

ROOT = Path(__file__).resolve().parent.parent
TEXTS_FILE = ROOT / "scripts" / ".audio-texts.json"
AUDIO_DIR = ROOT / "public" / "audio"
MANIFEST_FILE = ROOT / "src" / "content" / "audioManifest.ts"
VOICE = "fa-IR-DilaraNeural"
RATE = "-15%"  # slower than default — clearer for learners
CONCURRENCY = 4


def filename_for(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:16] + ".mp3"


def reencode_for_compatibility(src: Path, dest: Path) -> bool:
    """edge-tts's raw output is a 24kHz MPEG-2 Layer III stream with no
    Xing/VBR header (ffprobe has to *estimate* its duration from bitrate) —
    a real class of iOS Safari playback failure: AVFoundation's stricter MP3
    decoder can silently refuse to play files like this, even though
    desktop Chrome/Safari tolerate them fine. Re-encoding through ffmpeg to
    a standard 44.1kHz MPEG-1 stream with a proper header fixes it, at
    effectively the same file size (48kbps mono voice audio)."""
    result = subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-i", str(src), "-ar", "44100", "-ac", "1", "-b:a", "48k", str(dest)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  ffmpeg re-encode failed: {result.stderr.strip()}", file=sys.stderr)
        return False
    return dest.exists() and dest.stat().st_size > 0


async def synthesize_one(text: str, sem: asyncio.Semaphore) -> tuple[str, bool]:
    dest = AUDIO_DIR / filename_for(text)
    if dest.exists() and dest.stat().st_size > 0:
        return text, False
    async with sem:
        for attempt in range(3):
            try:
                with tempfile.TemporaryDirectory() as tmp:
                    raw = Path(tmp) / "raw.mp3"
                    communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
                    await communicate.save(str(raw))
                    if raw.exists() and raw.stat().st_size > 0 and reencode_for_compatibility(raw, dest):
                        return text, True
            except Exception as e:  # noqa: BLE001 - best-effort content pipeline, log and retry
                print(f"  retry {attempt + 1}/3 for {text!r}: {e}", file=sys.stderr)
                await asyncio.sleep(1.5)
        print(f"  FAILED: {text!r}", file=sys.stderr)
        return text, False


async def main() -> None:
    if not shutil.which("ffmpeg"):
        print("ffmpeg not found on PATH — required to re-encode clips for iOS Safari compatibility", file=sys.stderr)
        sys.exit(1)
    if not TEXTS_FILE.exists():
        print(f"missing {TEXTS_FILE} — run the tsx collector first (see module docstring)", file=sys.stderr)
        sys.exit(1)
    texts: list[str] = json.loads(TEXTS_FILE.read_text())
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)

    sem = asyncio.Semaphore(CONCURRENCY)
    results = await asyncio.gather(*(synthesize_one(t, sem) for t in texts))

    generated = sum(1 for _, ok in results if ok)
    failed = [t for t, ok in results if not ok and not (AUDIO_DIR / filename_for(t)).exists()]
    print(f"generated {generated} new clip(s); {len(texts) - generated} already present; {len(failed)} failed")

    manifest_entries = {t: f"audio/{filename_for(t)}" for t in texts if (AUDIO_DIR / filename_for(t)).exists()}
    lines = [
        "// AUTO-GENERATED by scripts/generate_audio.py — do not hand-edit.",
        "// Maps a Persian text string to its pre-generated pronunciation clip",
        "// (see src/lib/speech.ts). Regenerate after authoring new content:",
        "//   npx tsx scripts/collect-audio-text.ts > scripts/.audio-texts.json",
        "//   python3 scripts/generate_audio.py",
        "export const audioManifest: Record<string, string> = {",
    ]
    for text, path in sorted(manifest_entries.items()):
        lines.append(f"  {json.dumps(text, ensure_ascii=False)}: {json.dumps(path)},")
    lines.append("}")
    MANIFEST_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {MANIFEST_FILE} with {len(manifest_entries)} entries")

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
